import {
	createConfig,
	createTargetJSNodeOptions
} from "@asint/enkore/spec/factory"

import {getFilesToAutogenerate} from "./config/enkore/getFilesToAutogenerate.mts"

const isPublicRelease = (
	process.env?.RELEASE_VERSION ?? ""
).startsWith("vp")

export const config: unknown = createConfig({
	target: {
		name: "js-node",
		options: createTargetJSNodeOptions({
			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@asint": {
					registry: "anioSoftware"
				},
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				packageName: "@asint/enkore__spec",
				registry: "anioSoftware"
			}, {
				packageName: "@anio-software/enkore.spec",
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles: await getFilesToAutogenerate()
})
