import {getDefinedEntities} from "./getDefinedEntities.mjs"
import {generateAllEntitiesCode} from "./generateAllEntitiesCode.mjs"

let autogeneratedFiles = {}

const definedEntities = await getDefinedEntities()

autogeneratedFiles[`src/AllDefinedEntities.d.mts`] = () => {
	return generateAllEntitiesCode(definedEntities)
}

export default {
	realm: {
		name: "js",
		type: "package"
	},

	autogenerate: autogeneratedFiles
}
