import {getDefinedEntities} from "./getDefinedEntities.mjs"
import {generateAllEntitiesCode} from "./generateAllEntitiesCode.mjs"
import {getDefinedAPIs} from "./getDefinedAPIs.mjs"
import {generateAllAPIsCode} from "./generateAllAPIsCode.mjs"

let autogeneratedFiles = {}

const definedEntities = await getDefinedEntities()

autogeneratedFiles[`src/AllDefinedEntities.d.mts`] = () => {
	return generateAllEntitiesCode(definedEntities)
}

const definedAPIs = await getDefinedAPIs()

autogeneratedFiles[`src/AllDefinedAPIs.d.mts`] = () => {
	return generateAllAPIsCode(definedAPIs)
}

export default {
	realm: {
		name: "js",
		type: "package"
	},

	autogenerate: autogeneratedFiles
}
