import type {EnkoreAutogeneratedFile} from "#~export/__aggregatedExports.ts"
import type {AllEnkoreTargetOptions} from "#~src/AllEnkoreTargetOptions.ts"

import type {TargetIdentifier} from "@anio-software/enkore-private.primitives"
import type {TargetIdentifierToEntityName} from "#~src/TargetIdentifierToEntityName.ts"

import type {ToolchainSpecifiers} from "@anio-software/enkore-private.toolchain-types"

type Map = {
	[K in TargetIdentifier]: Extract<AllEnkoreTargetOptions, {
		entityKind: TargetIdentifierToEntityName<K>
	}>
}

type Targets = {
	[K in TargetIdentifier]: {
		name: K
		options: Map[K]
		_toolchain?: ToolchainSpecifiers
	}
}

export type Definition = {
	target: Targets[keyof Targets]

	autogeneratedFiles?: EnkoreAutogeneratedFile[]

	buildConstants?: Record<string, string>
}
