import type {EnkoreAutogeneratedFile} from "#~export/__aggregatedExports.mts"
import type {AllEnkoreTargets} from "#~src/AllEnkoreTargets.mts"

import type {TargetIdentifier} from "@anio-software/enkore-private.primitives"
import type {TargetIdentifierToEntityName} from "#~src/TargetIdentifierToEntityName.mts"

import type {ToolchainSpecifiers} from "@anio-software/enkore.toolchain-types"

type Map = {
	[K in TargetIdentifier]: Extract<AllEnkoreTargets, {
		entityKind: TargetIdentifierToEntityName<K>
	}>
}

type Targets = {
	[K in TargetIdentifier]: {
		name: K
		options: Map[K]
		_toolchain?: ToolchainSpecifiers
	}
}

export type Definition = {
	target: Targets[keyof Targets]

	autogeneratedFiles?: EnkoreAutogeneratedFile[]

	buildConstants?: Record<string, string>
}
