import type {
	EnkoreConfig,
	EnkoreRealmJSConfig,
	EnkoreRealmCConfig,
	EnkoreRealmWebConfig,
	EnkoreAutogeneratedFile,
	EnkoreNodeAPIMessage
} from "#~src/export/__star_export.mts"

import type {NodePackageJSON} from "@enkore/primitives"

export type Definition = {
	project: {
		root: string
		config: EnkoreConfig
	}

	emitMessage: (
		severity: EnkoreNodeAPIMessage["severity"],
		id: EnkoreNodeAPIMessage["id"],
		message: EnkoreNodeAPIMessage["message"]
	) => undefined

	realm: {
		getConfig: () => 
			EnkoreRealmJSConfig  |
			EnkoreRealmCConfig   |
			EnkoreRealmWebConfig

		getDependency: (dependencyName: string) => unknown
		getDependencyVersion: (dependencyName: string) => string
		getDependencyPackageJSON: (dependencyName: string) => NodePackageJSON
		getDependencyPath: (dependencyName: string) => string
	}

	addAutogeneratedFile: (file: EnkoreAutogeneratedFile) => undefined
}
