import {
	createAutogeneratedFile
} from "enkore/spec/factory"

type AutogeneratedFile = ReturnType<typeof createAutogeneratedFile>

export async function getFilesToAutogenerate(): Promise<AutogeneratedFile[]> {
	const files: AutogeneratedFile[] = []

	return files
}
