import {
	createAutogeneratedFile
} from "enkore/spec/factory"
import {fileURLToPath} from "node:url"
import path from "node:path"
import {getDefinedEntities} from "./getDefinedEntities.mts"
import {getDefinedAPIs} from "./getDefinedAPIs.mts"
import {generateAllEntitiesCode} from "./generateAllEntitiesCode.mts"
import {generateAllAPIsCode} from "./generateAllAPIsCode.mts"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.join(__dirname, "..", "..")

type AutogeneratedFile = ReturnType<typeof createAutogeneratedFile>

export async function getFilesToAutogenerate(): Promise<AutogeneratedFile[]> {
	const files: AutogeneratedFile[] = []

	const definedEntities = await getDefinedEntities()
	const definedAPIs = await getDefinedAPIs()

	files.push(createAutogeneratedFile({
		destinationPath: "project/src/AllDefinedEntities.mts",
		generator() {
			return generateAllEntitiesCode(definedEntities)
		}
	}))

	files.push(createAutogeneratedFile({
		destinationPath: "project/src/AllDefinedAPIs.mts",
		generator() {
			return generateAllAPIsCode(definedAPIs)
		}
	}))

	return files
}
