import type {DefineEntity} from "#~src/DefineEntity.d.mts"

import type {Definition as EnkoreAutogeneratedFile_V0_Rev0Definition} from "#~src/entities/EnkoreAutogeneratedFile/v0/rev0.d.mts"
import type {Definition as EnkoreBoilerplateFile_V0_Rev0Definition} from "#~src/entities/EnkoreBoilerplateFile/v0/rev0.d.mts"
import type {Definition as EnkoreConfig_V0_Rev0Definition} from "#~src/entities/EnkoreConfig/v0/rev0.d.mts"
import type {Definition as EnkoreCoreData_V0_Rev0Definition} from "#~src/entities/EnkoreCoreData/v0/rev0.d.mts"
import type {Definition as EnkoreCoreTargetDependency_V0_Rev0Definition} from "#~src/entities/EnkoreCoreTargetDependency/v0/rev0.d.mts"
import type {Definition as EnkoreCoreTargetDependencyInstallSpecification_V0_Rev0Definition} from "#~src/entities/EnkoreCoreTargetDependencyInstallSpecification/v0/rev0.d.mts"
import type {Definition as EnkoreLockFile_V0_Rev0Definition} from "#~src/entities/EnkoreLockFile/v0/rev0.d.mts"
import type {Definition as EnkoreNodeAPIOptions_V0_Rev0Definition} from "#~src/entities/EnkoreNodeAPIOptions/v0/rev0.d.mts"
import type {Definition as EnkoreProjectFile_V0_Rev0Definition} from "#~src/entities/EnkoreProjectFile/v0/rev0.d.mts"
import type {Definition as EnkoreRealmJSRuntimeContext_V0_Rev0Definition} from "#~src/entities/EnkoreRealmJSRuntimeContext/v0/rev0.d.mts"
import type {Definition as EnkoreRealmJSRuntimeContextOptions_V0_Rev0Definition} from "#~src/entities/EnkoreRealmJSRuntimeContextOptions/v0/rev0.d.mts"
import type {Definition as EnkoreRealmJSRuntimeProject_V0_Rev0Definition} from "#~src/entities/EnkoreRealmJSRuntimeProject/v0/rev0.d.mts"
import type {Definition as EnkoreTargetC_V0_Rev0Definition} from "#~src/entities/EnkoreTargetC/v0/rev0.d.mts"
import type {Definition as EnkoreTargetJSNode_V0_Rev0Definition} from "#~src/entities/EnkoreTargetJSNode/v0/rev0.d.mts"
import type {Definition as EnkoreTargetJSNone_V0_Rev0Definition} from "#~src/entities/EnkoreTargetJSNone/v0/rev0.d.mts"
import type {Definition as EnkoreTargetJSWeb_V0_Rev0Definition} from "#~src/entities/EnkoreTargetJSWeb/v0/rev0.d.mts"

export type EnkoreAutogeneratedFile_V0_Rev0 = DefineEntity<"EnkoreAutogeneratedFile", 0, 0, EnkoreAutogeneratedFile_V0_Rev0Definition>
export type EnkoreBoilerplateFile_V0_Rev0 = DefineEntity<"EnkoreBoilerplateFile", 0, 0, EnkoreBoilerplateFile_V0_Rev0Definition>
export type EnkoreConfig_V0_Rev0 = DefineEntity<"EnkoreConfig", 0, 0, EnkoreConfig_V0_Rev0Definition>
export type EnkoreCoreData_V0_Rev0 = DefineEntity<"EnkoreCoreData", 0, 0, EnkoreCoreData_V0_Rev0Definition>
export type EnkoreCoreTargetDependency_V0_Rev0 = DefineEntity<"EnkoreCoreTargetDependency", 0, 0, EnkoreCoreTargetDependency_V0_Rev0Definition>
export type EnkoreCoreTargetDependencyInstallSpecification_V0_Rev0 = DefineEntity<"EnkoreCoreTargetDependencyInstallSpecification", 0, 0, EnkoreCoreTargetDependencyInstallSpecification_V0_Rev0Definition>
export type EnkoreLockFile_V0_Rev0 = DefineEntity<"EnkoreLockFile", 0, 0, EnkoreLockFile_V0_Rev0Definition>
export type EnkoreNodeAPIOptions_V0_Rev0 = DefineEntity<"EnkoreNodeAPIOptions", 0, 0, EnkoreNodeAPIOptions_V0_Rev0Definition>
export type EnkoreProjectFile_V0_Rev0 = DefineEntity<"EnkoreProjectFile", 0, 0, EnkoreProjectFile_V0_Rev0Definition>
export type EnkoreRealmJSRuntimeContext_V0_Rev0 = DefineEntity<"EnkoreRealmJSRuntimeContext", 0, 0, EnkoreRealmJSRuntimeContext_V0_Rev0Definition>
export type EnkoreRealmJSRuntimeContextOptions_V0_Rev0 = DefineEntity<"EnkoreRealmJSRuntimeContextOptions", 0, 0, EnkoreRealmJSRuntimeContextOptions_V0_Rev0Definition>
export type EnkoreRealmJSRuntimeProject_V0_Rev0 = DefineEntity<"EnkoreRealmJSRuntimeProject", 0, 0, EnkoreRealmJSRuntimeProject_V0_Rev0Definition>
export type EnkoreTargetC_V0_Rev0 = DefineEntity<"EnkoreTargetC", 0, 0, EnkoreTargetC_V0_Rev0Definition>
export type EnkoreTargetJSNode_V0_Rev0 = DefineEntity<"EnkoreTargetJSNode", 0, 0, EnkoreTargetJSNode_V0_Rev0Definition>
export type EnkoreTargetJSNone_V0_Rev0 = DefineEntity<"EnkoreTargetJSNone", 0, 0, EnkoreTargetJSNone_V0_Rev0Definition>
export type EnkoreTargetJSWeb_V0_Rev0 = DefineEntity<"EnkoreTargetJSWeb", 0, 0, EnkoreTargetJSWeb_V0_Rev0Definition>

export type EnkoreAutogeneratedFile_V0 = EnkoreAutogeneratedFile_V0_Rev0
export type EnkoreBoilerplateFile_V0 = EnkoreBoilerplateFile_V0_Rev0
export type EnkoreConfig_V0 = EnkoreConfig_V0_Rev0
export type EnkoreCoreData_V0 = EnkoreCoreData_V0_Rev0
export type EnkoreCoreTargetDependency_V0 = EnkoreCoreTargetDependency_V0_Rev0
export type EnkoreCoreTargetDependencyInstallSpecification_V0 = EnkoreCoreTargetDependencyInstallSpecification_V0_Rev0
export type EnkoreLockFile_V0 = EnkoreLockFile_V0_Rev0
export type EnkoreNodeAPIOptions_V0 = EnkoreNodeAPIOptions_V0_Rev0
export type EnkoreProjectFile_V0 = EnkoreProjectFile_V0_Rev0
export type EnkoreRealmJSRuntimeContext_V0 = EnkoreRealmJSRuntimeContext_V0_Rev0
export type EnkoreRealmJSRuntimeContextOptions_V0 = EnkoreRealmJSRuntimeContextOptions_V0_Rev0
export type EnkoreRealmJSRuntimeProject_V0 = EnkoreRealmJSRuntimeProject_V0_Rev0
export type EnkoreTargetC_V0 = EnkoreTargetC_V0_Rev0
export type EnkoreTargetJSNode_V0 = EnkoreTargetJSNode_V0_Rev0
export type EnkoreTargetJSNone_V0 = EnkoreTargetJSNone_V0_Rev0
export type EnkoreTargetJSWeb_V0 = EnkoreTargetJSWeb_V0_Rev0

export type EnkoreAutogeneratedFile = EnkoreAutogeneratedFile_V0
export type EnkoreBoilerplateFile = EnkoreBoilerplateFile_V0
export type EnkoreConfig = EnkoreConfig_V0
export type EnkoreCoreData = EnkoreCoreData_V0
export type EnkoreCoreTargetDependency = EnkoreCoreTargetDependency_V0
export type EnkoreCoreTargetDependencyInstallSpecification = EnkoreCoreTargetDependencyInstallSpecification_V0
export type EnkoreLockFile = EnkoreLockFile_V0
export type EnkoreNodeAPIOptions = EnkoreNodeAPIOptions_V0
export type EnkoreProjectFile = EnkoreProjectFile_V0
export type EnkoreRealmJSRuntimeContext = EnkoreRealmJSRuntimeContext_V0
export type EnkoreRealmJSRuntimeContextOptions = EnkoreRealmJSRuntimeContextOptions_V0
export type EnkoreRealmJSRuntimeProject = EnkoreRealmJSRuntimeProject_V0
export type EnkoreTargetC = EnkoreTargetC_V0
export type EnkoreTargetJSNode = EnkoreTargetJSNode_V0
export type EnkoreTargetJSNone = EnkoreTargetJSNone_V0
export type EnkoreTargetJSWeb = EnkoreTargetJSWeb_V0

export type AllDefinedEntities = EnkoreAutogeneratedFile | EnkoreBoilerplateFile | EnkoreConfig | EnkoreCoreData | EnkoreCoreTargetDependency | EnkoreCoreTargetDependencyInstallSpecification | EnkoreLockFile | EnkoreNodeAPIOptions | EnkoreProjectFile | EnkoreRealmJSRuntimeContext | EnkoreRealmJSRuntimeContextOptions | EnkoreRealmJSRuntimeProject | EnkoreTargetC | EnkoreTargetJSNode | EnkoreTargetJSNone | EnkoreTargetJSWeb
