import type {DefineEntity} from "#~src/DefineEntity.d.mts"

import type {Definition as EnkoreAutogeneratedFile_V0_Rev0Definition} from "#~src/entities/EnkoreAutogeneratedFile/v0/rev0.d.mts"
import type {Definition as EnkoreBoilerplateFile_V0_Rev0Definition} from "#~src/entities/EnkoreBoilerplateFile/v0/rev0.d.mts"
import type {Definition as EnkoreConfig_V0_Rev0Definition} from "#~src/entities/EnkoreConfig/v0/rev0.d.mts"
import type {Definition as EnkoreCoreData_V0_Rev0Definition} from "#~src/entities/EnkoreCoreData/v0/rev0.d.mts"
import type {Definition as EnkoreCoreRealmDependency_V0_Rev0Definition} from "#~src/entities/EnkoreCoreRealmDependency/v0/rev0.d.mts"
import type {Definition as EnkoreCoreRealmDependencyInstallSpecification_V0_Rev0Definition} from "#~src/entities/EnkoreCoreRealmDependencyInstallSpecification/v0/rev0.d.mts"
import type {Definition as EnkoreLockFile_V0_Rev0Definition} from "#~src/entities/EnkoreLockFile/v0/rev0.d.mts"
import type {Definition as EnkoreNodeAPIOptions_V0_Rev0Definition} from "#~src/entities/EnkoreNodeAPIOptions/v0/rev0.d.mts"
import type {Definition as EnkoreProjectFile_V0_Rev0Definition} from "#~src/entities/EnkoreProjectFile/v0/rev0.d.mts"
import type {Definition as EnkoreRealmCConfig_V0_Rev0Definition} from "#~src/entities/EnkoreRealmCConfig/v0/rev0.d.mts"
import type {Definition as EnkoreRealmJSConfig_V0_Rev0Definition} from "#~src/entities/EnkoreRealmJSConfig/v0/rev0.d.mts"
import type {Definition as EnkoreRealmJSRuntimeContext_V0_Rev0Definition} from "#~src/entities/EnkoreRealmJSRuntimeContext/v0/rev0.d.mts"
import type {Definition as EnkoreRealmJSRuntimeContextOptions_V0_Rev0Definition} from "#~src/entities/EnkoreRealmJSRuntimeContextOptions/v0/rev0.d.mts"
import type {Definition as EnkoreRealmJSRuntimeProject_V0_Rev0Definition} from "#~src/entities/EnkoreRealmJSRuntimeProject/v0/rev0.d.mts"
import type {Definition as EnkoreRealmWebConfig_V0_Rev0Definition} from "#~src/entities/EnkoreRealmWebConfig/v0/rev0.d.mts"

export type EnkoreAutogeneratedFile_V0_Rev0 = DefineEntity<"EnkoreAutogeneratedFile", 0, 0, EnkoreAutogeneratedFile_V0_Rev0Definition>
export type EnkoreBoilerplateFile_V0_Rev0 = DefineEntity<"EnkoreBoilerplateFile", 0, 0, EnkoreBoilerplateFile_V0_Rev0Definition>
export type EnkoreConfig_V0_Rev0 = DefineEntity<"EnkoreConfig", 0, 0, EnkoreConfig_V0_Rev0Definition>
export type EnkoreCoreData_V0_Rev0 = DefineEntity<"EnkoreCoreData", 0, 0, EnkoreCoreData_V0_Rev0Definition>
export type EnkoreCoreRealmDependency_V0_Rev0 = DefineEntity<"EnkoreCoreRealmDependency", 0, 0, EnkoreCoreRealmDependency_V0_Rev0Definition>
export type EnkoreCoreRealmDependencyInstallSpecification_V0_Rev0 = DefineEntity<"EnkoreCoreRealmDependencyInstallSpecification", 0, 0, EnkoreCoreRealmDependencyInstallSpecification_V0_Rev0Definition>
export type EnkoreLockFile_V0_Rev0 = DefineEntity<"EnkoreLockFile", 0, 0, EnkoreLockFile_V0_Rev0Definition>
export type EnkoreNodeAPIOptions_V0_Rev0 = DefineEntity<"EnkoreNodeAPIOptions", 0, 0, EnkoreNodeAPIOptions_V0_Rev0Definition>
export type EnkoreProjectFile_V0_Rev0 = DefineEntity<"EnkoreProjectFile", 0, 0, EnkoreProjectFile_V0_Rev0Definition>
export type EnkoreRealmCConfig_V0_Rev0 = DefineEntity<"EnkoreRealmCConfig", 0, 0, EnkoreRealmCConfig_V0_Rev0Definition>
export type EnkoreRealmJSConfig_V0_Rev0 = DefineEntity<"EnkoreRealmJSConfig", 0, 0, EnkoreRealmJSConfig_V0_Rev0Definition>
export type EnkoreRealmJSRuntimeContext_V0_Rev0 = DefineEntity<"EnkoreRealmJSRuntimeContext", 0, 0, EnkoreRealmJSRuntimeContext_V0_Rev0Definition>
export type EnkoreRealmJSRuntimeContextOptions_V0_Rev0 = DefineEntity<"EnkoreRealmJSRuntimeContextOptions", 0, 0, EnkoreRealmJSRuntimeContextOptions_V0_Rev0Definition>
export type EnkoreRealmJSRuntimeProject_V0_Rev0 = DefineEntity<"EnkoreRealmJSRuntimeProject", 0, 0, EnkoreRealmJSRuntimeProject_V0_Rev0Definition>
export type EnkoreRealmWebConfig_V0_Rev0 = DefineEntity<"EnkoreRealmWebConfig", 0, 0, EnkoreRealmWebConfig_V0_Rev0Definition>

export type EnkoreAutogeneratedFile_V0 = EnkoreAutogeneratedFile_V0_Rev0
export type EnkoreBoilerplateFile_V0 = EnkoreBoilerplateFile_V0_Rev0
export type EnkoreConfig_V0 = EnkoreConfig_V0_Rev0
export type EnkoreCoreData_V0 = EnkoreCoreData_V0_Rev0
export type EnkoreCoreRealmDependency_V0 = EnkoreCoreRealmDependency_V0_Rev0
export type EnkoreCoreRealmDependencyInstallSpecification_V0 = EnkoreCoreRealmDependencyInstallSpecification_V0_Rev0
export type EnkoreLockFile_V0 = EnkoreLockFile_V0_Rev0
export type EnkoreNodeAPIOptions_V0 = EnkoreNodeAPIOptions_V0_Rev0
export type EnkoreProjectFile_V0 = EnkoreProjectFile_V0_Rev0
export type EnkoreRealmCConfig_V0 = EnkoreRealmCConfig_V0_Rev0
export type EnkoreRealmJSConfig_V0 = EnkoreRealmJSConfig_V0_Rev0
export type EnkoreRealmJSRuntimeContext_V0 = EnkoreRealmJSRuntimeContext_V0_Rev0
export type EnkoreRealmJSRuntimeContextOptions_V0 = EnkoreRealmJSRuntimeContextOptions_V0_Rev0
export type EnkoreRealmJSRuntimeProject_V0 = EnkoreRealmJSRuntimeProject_V0_Rev0
export type EnkoreRealmWebConfig_V0 = EnkoreRealmWebConfig_V0_Rev0

export type EnkoreAutogeneratedFile = EnkoreAutogeneratedFile_V0
export type EnkoreBoilerplateFile = EnkoreBoilerplateFile_V0
export type EnkoreConfig = EnkoreConfig_V0
export type EnkoreCoreData = EnkoreCoreData_V0
export type EnkoreCoreRealmDependency = EnkoreCoreRealmDependency_V0
export type EnkoreCoreRealmDependencyInstallSpecification = EnkoreCoreRealmDependencyInstallSpecification_V0
export type EnkoreLockFile = EnkoreLockFile_V0
export type EnkoreNodeAPIOptions = EnkoreNodeAPIOptions_V0
export type EnkoreProjectFile = EnkoreProjectFile_V0
export type EnkoreRealmCConfig = EnkoreRealmCConfig_V0
export type EnkoreRealmJSConfig = EnkoreRealmJSConfig_V0
export type EnkoreRealmJSRuntimeContext = EnkoreRealmJSRuntimeContext_V0
export type EnkoreRealmJSRuntimeContextOptions = EnkoreRealmJSRuntimeContextOptions_V0
export type EnkoreRealmJSRuntimeProject = EnkoreRealmJSRuntimeProject_V0
export type EnkoreRealmWebConfig = EnkoreRealmWebConfig_V0

export type AllDefinedEntities = EnkoreAutogeneratedFile | EnkoreBoilerplateFile | EnkoreConfig | EnkoreCoreData | EnkoreCoreRealmDependency | EnkoreCoreRealmDependencyInstallSpecification | EnkoreLockFile | EnkoreNodeAPIOptions | EnkoreProjectFile | EnkoreRealmCConfig | EnkoreRealmJSConfig | EnkoreRealmJSRuntimeContext | EnkoreRealmJSRuntimeContextOptions | EnkoreRealmJSRuntimeProject | EnkoreRealmWebConfig
