import type {DefineEntity} from "#~src/DefineEntity.d.mts"

import type {Definition as EnkoreAutogeneratedFile_V0_Rev0Definition} from "#~src/entities/EnkoreAutogeneratedFile/v0/rev0.d.mts"
import type {Definition as EnkoreBoilerplateFile_V0_Rev0Definition} from "#~src/entities/EnkoreBoilerplateFile/v0/rev0.d.mts"
import type {Definition as EnkoreConfig_V0_Rev0Definition} from "#~src/entities/EnkoreConfig/v0/rev0.d.mts"
import type {Definition as EnkoreCoreData_V0_Rev0Definition} from "#~src/entities/EnkoreCoreData/v0/rev0.d.mts"
import type {Definition as EnkoreJSRuntimeContext_V0_Rev0Definition} from "#~src/entities/EnkoreJSRuntimeContext/v0/rev0.d.mts"
import type {Definition as EnkoreJSRuntimeContextOptions_V0_Rev0Definition} from "#~src/entities/EnkoreJSRuntimeContextOptions/v0/rev0.d.mts"
import type {Definition as EnkoreJSRuntimeEmbeddedFile_V0_Rev0Definition} from "#~src/entities/EnkoreJSRuntimeEmbeddedFile/v0/rev0.d.mts"
import type {Definition as EnkoreJSRuntimeGlobalDataRecord_V0_Rev0Definition} from "#~src/entities/EnkoreJSRuntimeGlobalDataRecord/v0/rev0.d.mts"
import type {Definition as EnkoreJSRuntimeProject_V0_Rev0Definition} from "#~src/entities/EnkoreJSRuntimeProject/v0/rev0.d.mts"
import type {Definition as EnkoreLockFile_V0_Rev0Definition} from "#~src/entities/EnkoreLockFile/v0/rev0.d.mts"
import type {Definition as EnkoreNodeAPIOptions_V0_Rev0Definition} from "#~src/entities/EnkoreNodeAPIOptions/v0/rev0.d.mts"
import type {Definition as EnkoreProjectFile_V0_Rev0Definition} from "#~src/entities/EnkoreProjectFile/v0/rev0.d.mts"
import type {Definition as EnkoreTargetCOptions_V0_Rev0Definition} from "#~src/entities/EnkoreTargetCOptions/v0/rev0.d.mts"
import type {Definition as EnkoreTargetJSNodeOptions_V0_Rev0Definition} from "#~src/entities/EnkoreTargetJSNodeOptions/v0/rev0.d.mts"
import type {Definition as EnkoreTargetJSNoneOptions_V0_Rev0Definition} from "#~src/entities/EnkoreTargetJSNoneOptions/v0/rev0.d.mts"
import type {Definition as EnkoreTargetJSWebOptions_V0_Rev0Definition} from "#~src/entities/EnkoreTargetJSWebOptions/v0/rev0.d.mts"

export type EnkoreAutogeneratedFile_V0_Rev0 = DefineEntity<"EnkoreAutogeneratedFile", 0, 0, EnkoreAutogeneratedFile_V0_Rev0Definition>
export type EnkoreBoilerplateFile_V0_Rev0 = DefineEntity<"EnkoreBoilerplateFile", 0, 0, EnkoreBoilerplateFile_V0_Rev0Definition>
export type EnkoreConfig_V0_Rev0 = DefineEntity<"EnkoreConfig", 0, 0, EnkoreConfig_V0_Rev0Definition>
export type EnkoreCoreData_V0_Rev0 = DefineEntity<"EnkoreCoreData", 0, 0, EnkoreCoreData_V0_Rev0Definition>
export type EnkoreJSRuntimeContext_V0_Rev0 = DefineEntity<"EnkoreJSRuntimeContext", 0, 0, EnkoreJSRuntimeContext_V0_Rev0Definition>
export type EnkoreJSRuntimeContextOptions_V0_Rev0 = DefineEntity<"EnkoreJSRuntimeContextOptions", 0, 0, EnkoreJSRuntimeContextOptions_V0_Rev0Definition>
export type EnkoreJSRuntimeEmbeddedFile_V0_Rev0 = DefineEntity<"EnkoreJSRuntimeEmbeddedFile", 0, 0, EnkoreJSRuntimeEmbeddedFile_V0_Rev0Definition>
export type EnkoreJSRuntimeGlobalDataRecord_V0_Rev0 = DefineEntity<"EnkoreJSRuntimeGlobalDataRecord", 0, 0, EnkoreJSRuntimeGlobalDataRecord_V0_Rev0Definition>
export type EnkoreJSRuntimeProject_V0_Rev0 = DefineEntity<"EnkoreJSRuntimeProject", 0, 0, EnkoreJSRuntimeProject_V0_Rev0Definition>
export type EnkoreLockFile_V0_Rev0 = DefineEntity<"EnkoreLockFile", 0, 0, EnkoreLockFile_V0_Rev0Definition>
export type EnkoreNodeAPIOptions_V0_Rev0 = DefineEntity<"EnkoreNodeAPIOptions", 0, 0, EnkoreNodeAPIOptions_V0_Rev0Definition>
export type EnkoreProjectFile_V0_Rev0 = DefineEntity<"EnkoreProjectFile", 0, 0, EnkoreProjectFile_V0_Rev0Definition>
export type EnkoreTargetCOptions_V0_Rev0 = DefineEntity<"EnkoreTargetCOptions", 0, 0, EnkoreTargetCOptions_V0_Rev0Definition>
export type EnkoreTargetJSNodeOptions_V0_Rev0 = DefineEntity<"EnkoreTargetJSNodeOptions", 0, 0, EnkoreTargetJSNodeOptions_V0_Rev0Definition>
export type EnkoreTargetJSNoneOptions_V0_Rev0 = DefineEntity<"EnkoreTargetJSNoneOptions", 0, 0, EnkoreTargetJSNoneOptions_V0_Rev0Definition>
export type EnkoreTargetJSWebOptions_V0_Rev0 = DefineEntity<"EnkoreTargetJSWebOptions", 0, 0, EnkoreTargetJSWebOptions_V0_Rev0Definition>

export type EnkoreAutogeneratedFile_V0 = EnkoreAutogeneratedFile_V0_Rev0
export type EnkoreBoilerplateFile_V0 = EnkoreBoilerplateFile_V0_Rev0
export type EnkoreConfig_V0 = EnkoreConfig_V0_Rev0
export type EnkoreCoreData_V0 = EnkoreCoreData_V0_Rev0
export type EnkoreJSRuntimeContext_V0 = EnkoreJSRuntimeContext_V0_Rev0
export type EnkoreJSRuntimeContextOptions_V0 = EnkoreJSRuntimeContextOptions_V0_Rev0
export type EnkoreJSRuntimeEmbeddedFile_V0 = EnkoreJSRuntimeEmbeddedFile_V0_Rev0
export type EnkoreJSRuntimeGlobalDataRecord_V0 = EnkoreJSRuntimeGlobalDataRecord_V0_Rev0
export type EnkoreJSRuntimeProject_V0 = EnkoreJSRuntimeProject_V0_Rev0
export type EnkoreLockFile_V0 = EnkoreLockFile_V0_Rev0
export type EnkoreNodeAPIOptions_V0 = EnkoreNodeAPIOptions_V0_Rev0
export type EnkoreProjectFile_V0 = EnkoreProjectFile_V0_Rev0
export type EnkoreTargetCOptions_V0 = EnkoreTargetCOptions_V0_Rev0
export type EnkoreTargetJSNodeOptions_V0 = EnkoreTargetJSNodeOptions_V0_Rev0
export type EnkoreTargetJSNoneOptions_V0 = EnkoreTargetJSNoneOptions_V0_Rev0
export type EnkoreTargetJSWebOptions_V0 = EnkoreTargetJSWebOptions_V0_Rev0

export type EnkoreAutogeneratedFile = EnkoreAutogeneratedFile_V0
export type EnkoreBoilerplateFile = EnkoreBoilerplateFile_V0
export type EnkoreConfig = EnkoreConfig_V0
export type EnkoreCoreData = EnkoreCoreData_V0
export type EnkoreJSRuntimeContext = EnkoreJSRuntimeContext_V0
export type EnkoreJSRuntimeContextOptions = EnkoreJSRuntimeContextOptions_V0
export type EnkoreJSRuntimeEmbeddedFile = EnkoreJSRuntimeEmbeddedFile_V0
export type EnkoreJSRuntimeGlobalDataRecord = EnkoreJSRuntimeGlobalDataRecord_V0
export type EnkoreJSRuntimeProject = EnkoreJSRuntimeProject_V0
export type EnkoreLockFile = EnkoreLockFile_V0
export type EnkoreNodeAPIOptions = EnkoreNodeAPIOptions_V0
export type EnkoreProjectFile = EnkoreProjectFile_V0
export type EnkoreTargetCOptions = EnkoreTargetCOptions_V0
export type EnkoreTargetJSNodeOptions = EnkoreTargetJSNodeOptions_V0
export type EnkoreTargetJSNoneOptions = EnkoreTargetJSNoneOptions_V0
export type EnkoreTargetJSWebOptions = EnkoreTargetJSWebOptions_V0

export type AllDefinedEntities = EnkoreAutogeneratedFile | EnkoreBoilerplateFile | EnkoreConfig | EnkoreCoreData | EnkoreJSRuntimeContext | EnkoreJSRuntimeContextOptions | EnkoreJSRuntimeEmbeddedFile | EnkoreJSRuntimeGlobalDataRecord | EnkoreJSRuntimeProject | EnkoreLockFile | EnkoreNodeAPIOptions | EnkoreProjectFile | EnkoreTargetCOptions | EnkoreTargetJSNodeOptions | EnkoreTargetJSNoneOptions | EnkoreTargetJSWebOptions
