import type {EnkoreAutogeneratedFile} from "#~src/export/__star_export.mts"
import type {AllEnkoreTargets} from "#~src/AllEnkoreTargets.d.mts"

export type Definition = {
	target: AllEnkoreTargets

	autogeneratedFiles?: EnkoreAutogeneratedFile[]

	buildConstants?: Record<string, string>
}
