import type {EnkoreAutogeneratedFile} from "#~src/export/__star_export.mts"

export type Definition = {
	generateFactoryWithInstantiationFile: (
		options: {
			source: string
			destination: string
		}
	) => EnkoreAutogeneratedFile[]

	generateFactoryFile: (
		options: {
			source: string
			destination: string
		}
	) => EnkoreAutogeneratedFile[]
}
