// NB: this list is allowed to expand
// and is intentionally written by hand
export type Kinds = 
                    "EnkoreCoreData"                                |
                    "EnkoreCoreRealmDependencyInstallSpecification" |
                    "EnkoreCoreRealmDependency"                     |
                    "EnkoreLockFile"                                |
                    "EnkoreConfig"                                  |
                    "EnkoreAutoGeneratedFile"                       |
                    "EnkoreNodeAPIOptions"                          |
                    "EnkoreRealmJSConfig"                           |
                    "EnkoreRealmJSRuntimeProject"                   |
                    "EnkoreRealmJSRuntimeContext"                   |
                    "EnkoreRealmJSRuntimeContextOptions"            |
                    "EnkoreRealmWebConfig"                          |
                    "EnkoreRealmCConfig"                            |
                    "EnkoreMessage"
