// NB: this list is allowed to expand
// and is intentionally written by hand
export type Kinds = 
                    "EnkoreCoreData"                                |
                    "EnkoreCoreRealmDependencyInstallSpecification" |
                    "EnkoreCoreRealmDependency"                     |
                    "EnkoreLockFile"                                |
                    "EnkoreProjectFile"                             |
                    "EnkoreBoilerplateFile"                         |
                    "EnkoreConfig"                                  |
                    "EnkoreAutogeneratedFile"                       |
                    "EnkoreNodeAPIOptions"                          |
                    "EnkoreTargetJSNone"                            |
                    "EnkoreTargetJSNode"                            |
                    "EnkoreTargetJSWeb"                             |
                    "EnkoreRealmJSRuntimeProject"                   |
                    "EnkoreRealmJSRuntimeContext"                   |
                    "EnkoreRealmJSRuntimeContextOptions"            |
                    "EnkoreTargetWeb"                               |
                    "EnkoreTargetC"
