import type {ToolchainSpecifiers} from "@anio-software/enkore-private.toolchain-types"

export type Definition = {
	toolchain: ToolchainSpecifiers

	autogeneratedFiles: {
		[path: string]: {
			hash: string
		}
	}
}
