import type {ToolchainSpecifier} from "@anio-software/enkore-private.primitives"

export type Definition = {
	toolchain: ToolchainSpecifier

	autogeneratedFiles: {
		[path: string]: {
			hash: string
		}
	}
}
