import type {TargetIdentifier} from "@enkore/primitives"
import type {ValidToolchainCombinations} from "@enkore-types/toolchains"

export type Definition = {
	targetIdentifier: TargetIdentifier
	toolchain: ValidToolchainCombinations

	autogeneratedFiles: {
		[path: string]: {
			hash: string
		}
	}
}
