import type {ValidToolchainCombinations} from "@enkore-types/toolchains"

export type Definition = {
	toolchain: ValidToolchainCombinations

	autogeneratedFiles: {
		[path: string]: {
			hash: string
		}
	}
}
