import type {TargetIdentifier} from "@enkore/primitives"

export type Definition = {
	targetIdentifier: TargetIdentifier
	realmDependenciesStamp: string

	realmDependencies: {
		[dependencyName: string]: {
			version: string
			requestedVersion: string
		}
	}

	autogeneratedFiles: {
		[path: string]: {
			hash: string
		}
	}
}
