import type {EnkoreAutoGeneratedFile} from "#~src/export/__star_export.mts"

export type Definition = {
	generateWrapperAndFactoryFiles: (
		options: {
			source: string
			exportName: string
			destination: string
		}
	) => EnkoreAutoGeneratedFile[]

	generateFactoryFiles: (
		options: {
			source: string
			exportName: string
			destination: string
		}
	) => EnkoreAutoGeneratedFile[]
}
