// NB: this list is allowed to expand
// and is intentionally written by hand
export type Kinds = "EnkoreCoreData"                  |
                    "EnkoreLockFile"                  |
                    "EnkoreProjectFile"               |
                    "EnkoreBuildFile"                 |
                    "EnkoreBuildInfoFile"             |
                    "EnkoreBoilerplateFile"           |
                    "EnkoreConfig"                    |
                    "EnkoreAutogeneratedFile"         |
                    "EnkoreNodeAPIOptions"            |
                    "EnkoreJSBuildManifestFile"       |
                    "EnkoreJSRuntimeProject"          |
                    "EnkoreJSRuntimeGlobalDataRecord" |
                    "EnkoreJSRuntimeEmbeddedFile"     |
                    "EnkoreJSRuntimeContext"          |
                    "EnkoreJSRuntimeContextOptions"   |
                    "EnkoreTargetJSNoneOptions"       |
                    "EnkoreTargetJSWebOptions"        |
                    "EnkoreTargetJSNodeOptions"       |
                    "EnkoreTargetJSHybridOptions"     |
                    "EnkoreTargetJSHybridLiteOptions" |
//                    "EnkoreTargetJSXNoneOptions"    |
                    "EnkoreTargetJSXWebOptions"       |
//                    "EnkoreTargetJSXNodeOptions"    |
                    "EnkoreTargetJSXHybridOptions"    |
                    "EnkoreTargetCOptions"
