// NB: this list is allowed to expand
// and is intentionally written by hand
export type Kinds = "EnkoreCoreData"                  |
                    "EnkoreLockFile"                  |
                    "EnkoreProjectFile"               |
                    "EnkoreBoilerplateFile"           |
                    "EnkoreConfig"                    |
                    "EnkoreAutogeneratedFile"         |
                    "EnkoreNodeAPIOptions"            |
                    "EnkoreJSRuntimeProject"          |
                    "EnkoreJSRuntimeGlobalDataRecord" |
                    "EnkoreJSRuntimeEmbeddedFile"     |
                    "EnkoreJSRuntimeContext"          |
                    "EnkoreJSRuntimeContextOptions"   |
                    "EnkoreTargetCOptions"
