# This is CI/CD version 0.9.0
#
# Changelog
#
# v0.4.0 - 07.09.2024 (by eXory2024)
# Add environment variable "ANIO_CICD" for scripts to detect CI.
# "ANIO_CICD" contains the current CI/CD version.
#
# v0.5.0 - 21.09.2024 (by eXory2024)
# Use "npm ci" (require package-lock.json) instead of "npm i"
#
# v0.6.0 - 24.09.2024 (by eXory2024)
# Add manual "experimental" releases.
#
# v0.7.0 - 01.11.2024 (by eXory2024)
# Add repository name to environment (ANIO_CICD_REPO)
#
# v0.8.0 - 09.12.2024 (by eXory2024)
# Bump node version to v22
#
# v0.9.0 - 20.03.2025 (by eXory2024)
# Bump node version to v23
#

name: CI/CD

on:
  push:

jobs:
  # Run tests for on push
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
    env:
      ANIO_CICD: "v0.9.0"
      ANIO_CICD_REPO: "${{ github.repository }}"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install node modules (if present)"
        run: bash -c 'if [ -f package.json ]; then npm ci ; fi'

      - name: "Run .cicd/test.sh script (if present)"
        run: bash -c 'if [ -f ./.cicd/test.sh ]; then ./.cicd/test.sh ; fi'

  # Publish for tags starting with "v"
  publish:
    name: Deployment
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
    env:
      ANIO_CICD: "v0.9.0"
      ANIO_CICD_REPO: "${{ github.repository }}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
          registry-url: "https://registry.npmjs.org"

      - name: "Install node modules (if present)"
        run: bash -c 'if [ -f package.json ]; then npm ci ; fi'

      # Place private key and certificate in order to have
      # access to npm-registry.anio.software
      - name: "Setup runner private key and certificate"
        env:
          ANIO_NPM_REGISTRY_GITHUB_CICD_CERT: ${{ secrets.ANIO_NPM_REGISTRY_GITHUB_CICD_CERT }}
          ANIO_NPM_REGISTRY_GITHUB_CICD_PKEY: ${{ secrets.ANIO_NPM_REGISTRY_GITHUB_CICD_PKEY }}
        run: |
          touch ./.cicd/client.cert
          touch ./.cicd/client.pkey
          chmod 0600 ./.cicd/client.cert ./.cicd/client.pkey
          printf "%s" "$ANIO_NPM_REGISTRY_GITHUB_CICD_CERT" > ./.cicd/client.cert
          printf "%s" "$ANIO_NPM_REGISTRY_GITHUB_CICD_PKEY" > ./.cicd/client.pkey
          openssl x509 -in ./.cicd/client.cert -noout -text

      - name: "Setup npmrc file"
        run: |
          touch ./.npmrc
          printf "%s\n" "registry=https://npm-registry.anio.software" >> ./.npmrc
          printf "%s\n" "//npm-registry.anio.software/:keyfile=./.cicd/client.pkey" >> ./.npmrc
          printf "%s\n" "//npm-registry.anio.software/:certfile=./.cicd/client.cert" >> ./.npmrc
          printf "%s\n" "//npm-registry.anio.software/:_authToken=${{ secrets.ANIO_NPM_REGISTRY_GITHUB_CICD_TOKEN }}" >> ./.npmrc

      #
      # Make sure package.json's version field and
      # tag name are consistent.
      #
      - name: "Validate package.json version (if present)"
        run: bash -c 'if [ -f package.json ]; then clean_ver="$(printf "%s" "${{ github.ref_name }}" | cut -c2-)" ; grep -q "\"$clean_ver\"" package.json ; fi'

      - name: "Run .cicd/deploy.sh script"
        run: ./.cicd/deploy.sh
        env:
          RELEASE_VERSION: ${{ github.ref_name }}

          ANIO_SH_DEPLOY_URL: ${{ secrets.ANIO_SH_DEPLOY_URL }}
          ANIO_SH_DEPLOY_KEY: ${{ secrets.ANIO_SH_DEPLOY_KEY }}
